import type { Metadata } from 'next'
import { Roboto_Condensed } from 'next/font/google'
import './globals.css'
import Image from 'next/image'
import logoVirtual from '../../public/logo blanco.webp'

const inter = Roboto_Condensed({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Virtual Remote Partner',
  description: 'Generated by Virtual Remote Partner',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col items-center bg-gradient-to-tl from-[#00001e] to-[#010044] `}>
        <Image className='mt-4' src={logoVirtual} width={150} height={150} alt='logo virtual remote partner'/>
        {children}
      </body>
    </html>
  )
}
